web/scalica/micro/urls.py
from django.conf.urls import include, url

from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^home/$', views.home, name='home'),
    url(r'^friends/$', views.friendlist, name='friendlist'),
    url(r'^stream/(?P<user_id>[0-9]+)/$', views.stream, name='stream'),
    url(r'^image/(?P<image_id>.{36})/$', views.image, name='image'),
    url(r'^image/(?P<image_id>.{36})/tags$', views.tags, name='tags'),
    url(r'^post/$', views.post, name='post'),
    url(r'^follow/$', views.follow, name='follow'),
    url(r'^upload/$', views.upload, name='upload'),
    url(r'^register/$', views.register, name='register'),
    url('^', include('django.contrib.auth.urls'))
]

web/scalica/scalica/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^micro/', include('micro.urls', namespace="micro")),
    url(r'^admin/', include(admin.site.urls)),
]

web/scalica/micro/models.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.conf import settings

from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from django.forms import ModelForm, TextInput, FileInput

import uuid

# Helper functions

def uuidGen():
    x = uuid.uuid4()
    while True:
        try:
            Post.objects.get(id = x)
            x = uuid.uuid4()
        except Post.DoesNotExist:
            return x

# upload_to path determination
def profile_pic_path(instance, filename):
    return 'images/profiles/{0}.png'.format(instance.user.id)
def pic_path(instance, filename):
    # TODO: figure out how we want to format this
    # have to change the filename...what if the user tries posting something else with the same filename
    return 'images/uploads/{0}/{1}'.format(instance.user.username, filename)


# Models
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE,
                                related_name='profile')

    # TODO: make sure that on upload this is scaled down to a specified size
    # Default pic is 128*128...maybe use that
    profile_picture = models.ImageField(upload_to=profile_pic_path,
                                        default='images/profiles/user.png')

class Post(models.Model):
  user = models.ForeignKey(settings.AUTH_USER_MODEL)
  text = models.CharField(max_length=256, default="")
  pub_date = models.DateTimeField('date_posted')
  image = models.ImageField(upload_to=pic_path, null=True)
  has_faces = models.BooleanField(default=False)
  id = models.UUIDField(primary_key=True, default=uuidGen, editable=False)

  def __str__(self):
    if len(self.text) < 16:
      desc = self.text
    else:
      desc = self.text[0:16]
    return self.user.username + ':' + desc

class Tag(models.Model):
    tagNum = models.IntegerField()
    x = models.IntegerField()
    y = models.IntegerField()
    height = models.IntegerField()
    width = models.IntegerField()
    post = models.ForeignKey(Post, related_name = 'tags')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name = 'tagged_posts', null=True, on_delete = models.SET_NULL)
    @classmethod
    def create(cls, post, x, y, w, h, user):
        thisId = len(Post.objects.get(id = post.id).tags.all())
        book = cls(post=post, x=x, y=y, width=w, height=h, user=user, tagNum = thisId)
        return book

class Following(models.Model):
  follower = models.ForeignKey(settings.AUTH_USER_MODEL,
                               related_name="user_follows")
  followee = models.ForeignKey(settings.AUTH_USER_MODEL,
                               related_name="user_followed")
  follow_date = models.DateTimeField('follow date')
  def __str__(self):
    return self.follower.user.username + "->" + self.followee.user.username


# Profile creation/update functions
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        profile = Profile.objects.create(id=instance.id, user=instance)
@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


# Model Forms
class PostForm(ModelForm):
  class Meta:
    model = Post
    fields = ('text',)
    widgets = {
      'text': TextInput(attrs={'id' : 'input_post'}),
    }

class ImageUploadForm(ModelForm):
    class Meta:
        model = Post
        fields = ('image', 'text')
        widgets = {
          'image': FileInput(attrs={'accept': 'image/gif, image/jpeg, image/png, image/bmp, image/', 'value': 'Select Image'}),
        }

class FollowingForm(ModelForm):
  class Meta:
    model = Following
    fields = ('followee',)

class MyUserCreationForm(UserCreationForm):
  class Meta(UserCreationForm.Meta):
    help_texts = {
      'username' : '',
    }

web/scalica/micro/views.py
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.utils import timezone
from django.core.cache import cache
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt
from django.http import Http404


from .models import Following, Post, Tag
from .models import FollowingForm, ImageUploadForm, PostForm, MyUserCreationForm

import threading
import xmlrpclib
import Queue
import hashlib
import json

cache.set('threads', 0)
cache.set('maxThreads', 20)
workQueue = Queue.Queue(0)
rpc = xmlrpclib.ServerProxy("http://localhost:8080")


# Anonymous views
#################
def index(request):
  if request.user.is_authenticated():
    return home(request)
  else:
    return anon_home(request)

def anon_home(request):
  return render(request, 'micro/public.html')

def stream(request, user_id):
  # See if to present a 'follow' button
  form = None
  if request.user.is_authenticated() and request.user.id != int(user_id):
    try:
      f = Following.objects.get(follower_id=request.user.id,
                                followee_id=user_id)
    except Following.DoesNotExist:
      form = FollowingForm
  user = User.objects.get(pk=user_id)
  post_list = Post.objects.filter(user_id=user_id).order_by('-pub_date')
  paginator = Paginator(post_list, 10)
  page = request.GET.get('page')
  try:
    posts = paginator.page(page)
  except PageNotAnInteger:
    # If page is not an integer, deliver first page.
    posts = paginator.page(1)
  except EmptyPage:
    # If page is out of range (e.g. 9999), deliver last page of results.
    posts = paginator.page(paginator.num_pages)
  context = {
    'posts' : posts,
    'stream_user' : user,
    'form' : form,
  }
  return render(request, 'micro/stream.html', context)

def register(request):
  if request.method == 'POST':
    form = MyUserCreationForm(request.POST)
    new_user = form.save(commit=True)
    # Log in that user.
    user = authenticate(username=new_user.username,
                        password=form.clean_password2())
    if user is not None:
      login(request, user)
    else:
      raise Exception
    return home(request)
  else:
    form = MyUserCreationForm
  return render(request, 'micro/register.html', {'form' : form})

# Authenticated views
#####################
@login_required
def home(request):
  '''List of recent posts by people I follow'''
  try:
    my_post = Post.objects.filter(user=request.user).order_by('-pub_date')[0]
  except IndexError:
    my_post = None
  follows = [o.followee_id for o in Following.objects.filter(
    follower_id=request.user.id)]
  follows.append(request.user.id)
  try:
      post_list = Post.objects.filter(
          user_id__in=follows).order_by('-pub_date')[0:10]
  except:
      post_list = False
  context = {
    'post_list': post_list,
    'my_post': my_post,
    'post_form' : PostForm,
    'image_upload_form': ImageUploadForm
  }
  return render(request, 'micro/home.html', context)

# Allows to post something and shows my most recent posts.
@login_required
def post(request):
  if request.method == 'POST':
    form = PostForm(request.POST)
    new_post = form.save(commit=False)
    new_post.user = request.user
    new_post.pub_date = timezone.now()
    new_post.save()
    return home(request)
  else:
    form = PostForm
  return render(request, 'micro/post.html', {'form' : form})

def tags(request, image_id):
    if request.method == 'GET':
        try:
            print(image_id)
            image = Post.objects.get(id=image_id)
            print(image)
            tags = []
            for o in image.tags.all():
                if(o.user):
                    tags.append([o.tagNum, o.user.username])
                else:
                    tags.append([o.tagNum, o.user])
            return HttpResponse(json.dumps({'tags':tags}))
        except Post.DoesNotExist:
            raise Http404("Image does not exist")

@csrf_exempt
def image(request, image_id):
    if request.method == 'GET':
        try:
            image = Post.objects.get(id=image_id)
        except Post.DoesNotExist:
            return redirect('/micro')

        my_photo = False
        if request.user.is_authenticated() and request.user.id == image.user.id:
            my_photo = True
        has_faces = image.has_faces
        image_url = image.image.url
        curr_user = request.user
        faces_in_photo = image.tags.all()
        tagged_users = [o.user for o in image.tags.all() if not o.user == None]
        tagged_users = list(set(tagged_users))
        scaleFactor = float(600)/max(image.image.height, image.image.width)
        if(scaleFactor > 1):
            scaleFactor = 1
        scaleFactor = 1/scaleFactor
        context = {
            'my_photo': my_photo,
            'image_url': image_url,
            'has_faces': has_faces,
            'user': curr_user,
            'tagged_users': {'tags': tagged_users},
            'faces_in_photo': faces_in_photo,
            'scaleFactor': scaleFactor
        }

        return render(request, 'micro/image.html', context)
    elif request.method == 'POST':
        try:
            image = Post.objects.get(id=image_id)
        except Post.DoesNotExist:
            raise Http404("Failed")
        if request.user.is_authenticated() and request.user.id == image.user.id:
            if(request.POST.get('user')):
                tag_name = request.POST.get('user')
                try:
                    user= User.objects.get(username = tag_name)
                    print user
                    print request.POST.get('tag')
                    tag = image.tags.get(tagNum = request.POST.get('tag'))
                    print tag
                    tag.user = user
                    tag.save()
                    print 'saved'
                except:
                    pass
            print 'authed'
        print request.POST.get('user')
        return HttpResponse('success')
    else:
        raise Http404("Failed")

@login_required
def follow(request):
  if request.method == 'POST':
    form = FollowingForm(request.POST)
    new_follow = form.save(commit=False)
    new_follow.follower = request.user
    new_follow.follow_date = timezone.now()
    new_follow.save()
    return home(request)
  else:
    form = FollowingForm
  return render(request, 'micro/follow.html', {'form' : form})

@login_required
def friendlist(request):
    if request.method == 'GET':
        follows = [o.followee.username for o in Following.objects.filter(
            follower_id=request.user.id)]
        follows.append(request.user.username)

        return HttpResponse(json.dumps({'friends': follows}), content_type="application/json")
    else:
        return redirect('/micro')

@login_required
def upload(request):
    if request.method == 'POST':
        form = ImageUploadForm(request.POST, request.FILES)
        if form.is_valid():
            new_pic = form.save(commit=False)
            new_pic.user = request.user
            new_pic.pub_date = timezone.now()
            new_pic.save()
            redir = "/micro/image/" + str(new_pic.id)
            if(cache.get('threads') < cache.get('maxThreads')):
                image_thread = ImageProcessingThread(new_pic.id, workQueue)
                image_thread.start()
                print 'started thread'
                cache.incr('threads')
            else:
                print cache.get('threads')
                print cache.get('maxThreads')
                print 'queued'
                workQueue.put(new_pic.id)
            return redirect(redir)
    else:
        form = ImageUploadForm()
    return render(request, 'micro/upload.html', {'form': form})

def processPicture(pic_id, q):
    pic = Post.objects.get(id=pic_id)
    faceArr = rpc.face(pic.image.path)
    print 'called rpc'
    if type(faceArr) is list and len(faceArr) > 0:
        for i in faceArr:
            new_tag = Tag.create(pic, i[0], i[1], i[2], i[3], None)
            new_tag.save()
        pic.has_faces = True
        print 'face detected'

    pic.save()

    print 'checking q'
    while(not q.empty()):
        pic_id = q.get()
        pic = Picture.objects.get(id=pic_id)
        faceArr = rpc.face(pic.image.path)
        if type(faceArr) is list and len(faceArr) > 0:
            pic.has_faces = True
            # for now, just throwing out the array

        pic.save()


class ImageProcessingThread(threading.Thread):
    def __init__(self, image_id, q, *args, **kwargs):
        self.image_id = image_id
        self.q = q
        super(ImageProcessingThread, self).__init__(*args, **kwargs)

    def run(self):
        print 'processing'
        processPicture(self.image_id, self.q)
        print 'processed'
        cache.decr('threads')

web/scalica/micro/templates/micro/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
  <link rel="stylesheet" type="text/css" href="{% static 'micro/style.css' %}" />
  <title>Scalica</title>
</head> 
<body>
  <div id="header">
    {% if user.is_authenticated %}
      {{ user.username }}
      <a href="{% url 'micro:logout' %}">Log Out</a>
    {% else %}
      <a href="{% url 'micro:login' %}">Log In</a>
    {% endif %}
    {% block header %}{% endblock header %}
  </div>
  <div id="sidebar">
    {% block sidebar %}{% endblock sidebar %}
  </div>
  <div id="content">
    {% block content %}{% endblock content %}
  </div>
  <div id="footer">
    <p>Copyright Scalica</p>
    {% block footer %}{% endblock footer %}
  </div>
</body>
</html>

web/scalica/micro/templates/micro/base_simple.html
{% extends "base.html" %}
{% block page %}
<div class="wrapper">
<div id="content" class="clearfix">
{% block content %}
{% endblock %}
</div>
</div>
{% endblock %}

web/scalica/micro/templates/micro/follow.html
{% extends "micro/base.html" %}
{% block content %}
<form action="/micro/follow/" method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Submit" />
</form>
{% endblock %}

web/scalica/micro/templates/micro/home.html
{% extends "micro/base.html" %}
{% load humanize %}
{% load staticfiles %}
{% block sidebar %}
<img src="{{ user.profile.profile_picture.url }}" alt="Profile Picture"/> <br>
{{ user.username }}

{% endblock %}
{% block content %}
<div id="status">
{% if my_post %}
  {% if my_post.image %}
    <a href="/micro/image/{{my_post.id}}">
        <img class="imgpost" src="{{ my_post.image.url }}"/><br />
    </a>
  {% endif %}
 {{ my_post.text }} ({{ my_post.pub_date|naturaltime }})
{% endif %}
</div>

<div id="post-container">
  <div id="post-form" class="half-column">
    <form action="/micro/post/" method="post">
      {% csrf_token %}
      {{ post_form.text }}
      <input type="submit" value="Post" />
    </form>
  </div>

  <div id="image-upload-form" class="half-column">
    <form enctype="multipart/form-data" action="/micro/upload/" method="post">
      {% csrf_token %}
      {{ image_upload_form.text }}
      {{ image_upload_form.image }}
      <input type="submit" value="Upload Image" />
    </form>
  </div>
</div>

<div>
{% if post_list %}
  <table id="postlist">
    {% for post in post_list %}
      <tr>
        <td>
          <!-- TODO: this should get the url of the user's small profile picture -->
          <img src="{% static 'micro/uploads/images/profiles/user_s.png' %}" alt="Generic User"/>
        </td>
        <td>
          {% if post.image %}
          <a href="/micro/image/{{post.id}}">
              <img class="imgpost" src="{{ post.image.url }}"/><br />
          </a>
          {% endif %}
          {{ post.text }}
        </td>
      </tr>
      <tr>
        <td></td>
        <td>
          <a href="{% url 'micro:stream' post.user_id %}">
            {{ post.user.username }}
          </a>
          ({{ post.pub_date|naturaltime }})
        </td>
      </tr>
    {% endfor %}
  </table>
{% else %}
  <p>No posts are available.</p>
{% endif %}
</div>
{% endblock %}

web/scalica/micro/templates/micro/image.html
{% extends "micro/base.html" %}
{% load humanize %}
{% load staticfiles %}
{% block sidebar %}

<script src="{% static '/micro/javascripts/tagimage.js' %}"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="{% static '/micro/javascripts/tmp.js' %}"></script>
<img src="{{ user.profile.profile_picture.url }}" alt="Generic User"/> <br>
{{ user.username }}

{% endblock %}

{% block content %}
<div>
    <div class="half-column">
        {% for face in faces_in_photo %}
        <div id="{{ face.tagNum }}" class="tagcontainer" style="margin-left:{% widthratio face.x scaleFactor 1 %}px;margin-top:{% widthratio face.y scaleFactor 1 %}px;">
          <div class="tagbox" style="width:{% widthratio face.width scaleFactor 1 %}px;height:{% widthratio face.height scaleFactor 1 %}px;"></div>
          <div class='tagpage'></div>
        </div>
        {% endfor %}
        <img id="img-page-pic" src="{{ image_url }}" {% if has_faces %} class="has_faces" {% endif %}/>
    </div>
    <div id="tagged-list" class="half-column">
        <p>Friends in this photo:</p>
        <ul id='taglist'>
            {% for tag in tagged_users.tags %}
                <li>{{ tag }}</li>
            {% endfor %}
        </ul>
    </div>
</div>

{% if my_photo %}
<div id='tagpage'></div>
{% endif %}

{% endblock %}

web/scalica/micro/templates/micro/post.html
{% extends "micro/base.html" %}
{% block content %}
<form action="/micro/post/" method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Submit" />
</form>
{% endblock %}

web/scalica/micro/templates/micro/public.html
{% extends "micro/base.html" %}
{% block content %}
  <h1>Welcome to Scalica</h1></br>
  New Users: <a href="{% url 'micro:register' %}">Register</a> </br>
  Existing Users: <a href="{% url 'micro:login' %}">Log In</a>
{% endblock %}

web/scalica/micro/templates/micro/register.html
{% extends "micro/base.html" %}
{% block content %}
<form action="/micro/register/" method="post">
<table class="registerTable">
  {% csrf_token %}
  {{ form.as_table }}
</table>
  <input type="submit" value="Submit" />
</form>
{% endblock %}

web/scalica/micro/templates/micro/stream.html
{% extends "micro/base.html" %}
{% load humanize %}
{% load staticfiles %}
{% block sidebar %}

<img src="{{ stream_user.profile.profile_picture.url }}" alt="Generic User"/> <br>
{{ stream_user.username }}
{% if form %}
  <form action="/micro/follow/" method="post">
    {% csrf_token %}
    <input type="hidden" id="id_followee" name="followee" value="{{ stream_user.id }}" />
    <input type="submit" value="Follow" />
  </form>
{% endif %}
{% endblock %}
{% block content %}
{% for post in posts %}
  <li>
    {% if post.image %}
    <img src="{{ post.image.url }}" width="64" />
    {% endif %}
    {{ post.text }} ({{ post.pub_date|naturaltime }})
  </li>
{% endfor %}
{# TODO: see complete pagination example in Django doc for more #}
{% endblock %}

web/scalica/micro/templates/micro/temptagpage.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
  <link rel='stylesheet' type='text/css' href="{% static 'micro/style.css' %}" />
  <script src="{% static '/javascripts/tagimage.js' %}"></script>
  <h1>Test Page</h1>
</head>
<body>
  <img src='{% static '/micro/uploads/images/profiles/user.png'%}'/>
  <div id = "tagpage">
  </div>
</body>
</html>

web/scalica/micro/templates/micro/upload.html
{% extends "micro/base.html" %}
{% block content %}
<form enctype="multipart/form-data" action="/micro/upload/" method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Submit" />
</form>
{% endblock %}